// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOCBF3KSDZRP21RTwJs0rfVBURRenOa0Y',
    appId: '1:97678584490:web:d92fd1f67c97926b70fed3',
    messagingSenderId: '97678584490',
    projectId: 'flutterfirenotes-14037',
    authDomain: 'flutterfirenotes-14037.firebaseapp.com',
    storageBucket: 'flutterfirenotes-14037.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVClHaHqSkTYT5XHCTJ2scuk90f9CJqY',
    appId: '1:97678584490:android:90ff45df53d42e7e70fed3',
    messagingSenderId: '97678584490',
    projectId: 'flutterfirenotes-14037',
    storageBucket: 'flutterfirenotes-14037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkiR7xDA5TuIZE19_Fod1jdWgmL_SKJP4',
    appId: '1:97678584490:ios:90991a26e495922870fed3',
    messagingSenderId: '97678584490',
    projectId: 'flutterfirenotes-14037',
    storageBucket: 'flutterfirenotes-14037.appspot.com',
    iosClientId: '97678584490-d6te34m4e4sla77onk8valcm6lrd63lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkiR7xDA5TuIZE19_Fod1jdWgmL_SKJP4',
    appId: '1:97678584490:ios:90991a26e495922870fed3',
    messagingSenderId: '97678584490',
    projectId: 'flutterfirenotes-14037',
    storageBucket: 'flutterfirenotes-14037.appspot.com',
    iosClientId: '97678584490-d6te34m4e4sla77onk8valcm6lrd63lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp',
  );
}
